services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        pull_policy: build

    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        pull_policy: build
