//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "auth_sessions")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub token_hash: String,
	pub username: String,
	pub expires_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::users::Entity",
		from = "Column::Username",
		to = "super::users::Column::Username",
		on_update = "Cascade",
		on_delete = "Cascade"
	)]
	Users,
}

impl Related<super::users::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Users.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
